import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './GlobalRedux/provider';
import Header from "../components/header/header"
import Navbar from "../components/navbar/navbar"
import Footer from '@/components/footer/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className="bg-white" lang="en">
      <Providers>
      <body className={inter.className}>
        <Header/>
        <Navbar/>
        <div className='flex justify-center'>
          {children}
        </div>
        <Footer/>
        </body>
      </Providers>
    </html>
  )
}
